apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cost-optimizer-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: k8s-cost-optimizer-controller-manager
      containers:
      - name: manager
        image: controller:latest
        command:
        - /manager
        args:
        - --metrics-addr=:8080
        - --enable-leader-election
